version: '3'

services:
  db:
    build: 
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: semestral_ps01
    environment:
      - POSTGRES_PASSWORD=1029jdsdlaksmdpowj1309u12plmsd
      - POSTGRES_USER=django
      - POSTGRES_DB=django
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    container_name: semestral_dj01
    command: bash -c "/code/utilities/wait-for-it.sh postgres:5432 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=1029jdsdlaksmdpowj1309u12plmsd
      - DB_USER=django
      - DB_NAME=django
      - DB_HOST=db
      - DB_PORT=5432
      - IN_DOCKER=1
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code
      - ./src/media:/code/media
      - ./utilities:/code/utilities
    restart: always
