version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    container_name: semestral_dj01
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code
      - ./src/media:/code/media
    restart: always
