# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', null=True, verbose_name='Descripci\xf3n')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='C\xf3digo')),
                ('facultad', models.CharField(blank=True, choices=[('0', 'Facultad de Sistemas'), ('1', 'Facultad de Industrial'), ('2', 'Facultad de Civil'), ('3', 'Facultad de El\xe9ctrica')], default='0', max_length=30, null=True, verbose_name='G\xe9nero')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_de_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizaci\xf3n')),
            ],
            options={
                'ordering': ['facultad', 'nombre'],
                'db_table': 'asignaturas',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
    ]
