# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0003_asignatura_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Apellido')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('genero', models.CharField(blank=True, choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('otros', 'Otros')], default='otros', max_length=30, null=True, verbose_name='G\xe9nero')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Salario')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_de_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizaci\xf3n')),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignaturas.Asignatura', verbose_name='Asignatura')),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'estudiantes',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
